export {
  LEXER_ASSIGNMENT,
  LEXER_COMMA,
  LEXER_OBJECT_OPEN,
  LEXER_OBJECT_CLOSE,
  LEXER_ARRAY_OPEN,
  LEXER_ARRAY_CLOSE,
  LEXER_STRING,
  LEXER_SINGLELINE_COMMENT,
  LEXER_MULTILINE_COMMENT_OPEN,
  LEXER_MULTILINE_COMMENT_CLOSE,
  LEXER_NEW_LINE,
  LEXER_WHITESPACE,
  LEXER_RAW,
  LEXER_FUNCTION,
  LEXER_FUNCTION_OPEN,
  LEXER_FUNCTION_CLOSE,
  TOKEN_RAW,
  CONST_ARRAY,
  CONST_STRING,
  CONST_RAW,
};

const LEXER_ASSIGNMENT = 'ASSIGNMENT';
const LEXER_COMMA = 'COMMA';
const LEXER_OBJECT_OPEN = 'OBJECT_OPEN';
const LEXER_OBJECT_CLOSE = 'OBJECT_CLOSE';
const LEXER_ARRAY_OPEN = 'ARRAY_OPEN';
const LEXER_ARRAY_CLOSE = 'ARRAY_CLOSE';
const LEXER_STRING = 'STRING';
const LEXER_SINGLELINE_COMMENT = 'SINGLELINE_COMMENT';
const LEXER_MULTILINE_COMMENT_OPEN = 'MULTILINE_COMMENT_OPEN';
const LEXER_MULTILINE_COMMENT_CLOSE = 'MULTILINE_COMMENT_CLOSE';
const LEXER_NEW_LINE = 'NEW_LINE';
const LEXER_WHITESPACE = 'WHITESPACE';
const LEXER_RAW = 'RAW';
const LEXER_FUNCTION = 'FUNCTION';
const LEXER_FUNCTION_OPEN = 'FUNCTION_OPEN';
const LEXER_FUNCTION_CLOSE = 'FUNCTION_CLOSE';

const TOKEN_RAW: AHOCON.LexerToken = {
  name: LEXER_RAW,
  regex: /./,
};

const CONST_ARRAY = 'ARRAY';
const CONST_STRING = LEXER_STRING;
const CONST_RAW = LEXER_RAW;
